import error from '../common/pages/error.js'
import pages from '../common/pages/index.js'
import contact from '../common/pages/contact/index.js'
import input from '../common/pages/contact/input.js'
import list from '../common/pages/contact/list.js'
